import type { NextPage } from "next";
import Head from "next/head";
import { Canvas } from "../Components/Canvas";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.getAll"]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="overflow-hidden">
        <Canvas/>
      </div>
    </>
  );
};

export default Home;
